### ISSUE TITLE
Condition checker

### ISSUE THREAD

**Issue by mzolfaghari94** [sslab-gatech/apisan#1]
I can't understand the algorithm of your condition checker. Can you please explain what you have done to find the bugs?

**Comment by jakkdu** [comment]
Hi, it tries to get the constraints that appear together.
Especially, we can detect bug in OpenSSL using that.
Maybe you can see 67~73 pages of our slide(https://www.usenix.org/sites/default/files/conference/protected-files/security16_slides-yun.pdf)
Thanks.

**Comment by mzolfaghari94** [comment]
Thanks.
