### ISSUE TITLE
Semantic beliefs

### ISSUE THREAD

**Issue by mzolfaghari94** [sslab-gatech/apisan#2]
Hi,
I checked the apisan code, but I couldn't find where you extract the semantic beliefs (as explained in your paper). Do you extract the semantic belief in your code or just check for the minor uses?
Thanks.

**Comment by jakkdu** [comment]
Hi. It's hard to say 'just' check for the minor uses. 
The semantic believes are the majority patterns of API uses, 
and minor uses are the complement of them.

We don't save the semantic believes in dedicated structures, 
but to get minor uses, we extract the semantic belief.
The pattern that is more than threshold is actually the semantic belief. 
Thanks.

**Comment by mzolfaghari94** [comment]
Thanks for your complete answer.
