### ISSUE TITLE
How to use clang to complie linux kernel into LLVM IR?

### ISSUE THREAD

**Issue by daydayup40** [sslab-gatech/apisan#5]
How to use clang to complie linux kernel into LLVM IR?

**Comment by meng-xu** [comment]
(Copied from the email I sent to you)

As of now, most part of the Linux kernel has built-in support
for being compiled with LLVM by just adding CC=clang before
make.

For details, check https://lkml.org/lkml/2017/11/22/943 and
https://lwn.net/Articles/734071/ for the latest progress.

There are also wrappers that help you with the process, for
example, https://github.com/ramosian-glider/clang-kernel-build
(There are many on GitHub).

The very old schooled way (not sure whether it is still working now)
is via the LLVMLinux proeject (https://wiki.linuxfoundation.org/llvmlinux).
